create table hotel (id bigint generated by default as identity, nome varchar(255), numero_adultos_apartamento integer, numero_apartamento integer, numero_comodos_apartamento integer, numero_criancas_apartamento integer, percent_hotel numeric(38,2), primary key (id));
create table reserva (id bigint generated by default as identity, data_fim date, data_inicio date, numero_adultos integer, numero_comodos integer, numero_criancas integer, usuario_id bigint, valor numeric(38,2), hotel_id bigint, primary key (id));
alter table if exists hotel drop constraint if exists UKaer76hle57hskt83sd75dbtjb;
alter table if exists hotel add constraint UKaer76hle57hskt83sd75dbtjb unique (numero_apartamento);
alter table if exists reserva add constraint FKgve13jsoas3vq4xoo73lur8kv foreign key (hotel_id) references hotel;

INSERT INTO Hotel (nome, numero_Apartamento, numero_Adultos_Apartamento, numero_Criancas_Apartamento, numero_Comodos_Apartamento, percent_Hotel)
VALUES ('Hotel Bella Vista', 101, 2, 1, 3, 0.40);

INSERT INTO Hotel (nome, numero_Apartamento, numero_Adultos_Apartamento, numero_Criancas_Apartamento, numero_Comodos_Apartamento, percent_Hotel)
VALUES ('Hotel Maravilha', 102, 3, 2, 4, 0.25);

INSERT INTO Hotel (nome, numero_Apartamento, numero_Adultos_Apartamento, numero_Criancas_Apartamento, numero_Comodos_Apartamento, percent_Hotel)
VALUES ('Hotel Paraíso', 103, 2, 2, 3, 0.15);

INSERT INTO Hotel (nome, numero_Apartamento, numero_Adultos_Apartamento, numero_Criancas_Apartamento, numero_Comodos_Apartamento, percent_Hotel)
VALUES ('Hotel Luxor', 104, 4, 1, 5, 0.30);

INSERT INTO Hotel (nome, numero_Apartamento, numero_Adultos_Apartamento, numero_Criancas_Apartamento, numero_Comodos_Apartamento, percent_Hotel)
VALUES ('Hotel Vista Alegre', 105, 3, 3, 4, 0.20);